spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://auth-postgres:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
server.port=8083

server.port=4005
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=myVeryLongSecretKeyForJwtGeneration123456789
jwt.expiration=86400000
spring.main.allow-bean-definition-overriding=true