spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://auth-postgres:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
server.port=8083

springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=myVeryLongSecretKeyForJwtGeneration123456789
jwt.expiration=86400000
spring.main.allow-bean-definition-overriding=true

# Ensure data.sql runs for non-embedded databases
# For Spring Boot 2.5+ use `spring.sql.init.mode`; older versions use `spring.datasource.initialization-mode`
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true