spring.application.name=transaction-service

spring.application.name=transactionservice

spring.datasource.url=jdbc:postgresql://transaction-postgres:5432/transactiondb
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
server.port=8082


grpc.client.account-service.address=static://account-service-app:9091
grpc.client.account-service.negotiationType=PLAINTEXT
