spring:
  application:
    name: apigateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # APIs
            - id: customer-service
              uri: http://customer-service-app:8080
              predicates:
                - Path=/api/customers/**
              filters:
                - StripPrefix=1

            - id: account-service
              uri: http://account-service-app:8081
              predicates:
                - Path=/api/accounts/**
              filters:
                - StripPrefix=1

            - id: transaction-service
              uri: http://transaction-service-app:8082
              predicates:
                - Path=/api/transactions/**
              filters:
                - StripPrefix=1

            # Swagger
            - id: customer-service-swagger
              uri: http://customer-service-app:8080
              predicates:
                - Path=/api-docs/customers
              filters:
                - RewritePath=/api-docs/customers, /v3/api-docs

            - id: account-service-swagger
              uri: http://account-service-app:8081
              predicates:
                - Path=/api-docs/accounts
              filters:
                - RewritePath=/api-docs/accounts, /v3/api-docs

            - id: transaction-service-swagger
              uri: http://transaction-service-app:8082
              predicates:
                - Path=/api-docs/transactions
              filters:
                - RewritePath=/api-docs/transactions, /v3/api-docs

server:
  port: 4000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: gateway,health
