spring:
  application:
    name: apigateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # ── API Routes ─────────────────────────────────────────

            - id: auth-service
              uri: http://auth-service-app:8083
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: customer-service
              uri: http://customer-service-app:8080
              predicates:
                - Path=/api/customers/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: account-service
              uri: http://account-service-app:8081
              predicates:
                - Path=/api/accounts/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: transaction-service
              uri: http://transaction-service-app:8082
              predicates:
                - Path=/api/transactions/**
              filters:
                - StripPrefix=1
                - JwtValidation

            # ── API Docs JSON ──────────────────────────────────────

            - id: customer-service-api-docs
              uri: http://customer-service-app:8080
              predicates:
                - Path=/api-docs/customers/**
              filters:
                - RewritePath=/api-docs/customers, /api-docs

            - id: account-service-api-docs
              uri: http://account-service-app:8081
              predicates:
                - Path=/api-docs/accounts/**
              filters:
                - RewritePath=/api-docs/accounts, /api-docs

            - id: transaction-service-api-docs
              uri: http://transaction-service-app:8082
              predicates:
                - Path=/api-docs/transactions/**
              filters:
                - RewritePath=/api-docs/transactions, /api-docs
server:
  port: 4000
