spring.application.name=accountservice

spring.datasource.url=jdbc:postgresql://account-postgres:5432/accountdb
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
server.port=8081

grpc.server.port=9091
grpc.client.customer-service.address=static://customer-service-app:9090
grpc.client.customer-service.negotiationType=PLAINTEXT
