spring.application.name=tranactionservice

spring.datasource.url=jdbc:postgresql://transaction-postgres:5432/transactiondb
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
server.port=8082
